### ISSUE TITLE
SerializationException when MailChimp returns error page instead of an API result

### ISSUE THREAD

**Issue by htoomik** [danesparza/MailChimp.NET#155]
In some cases (and I haven't been able to determine when this happens) MailChimp returns an error page instead of an API response - html instead of json. Possibly when the service is down?

MailChimpManager throws SerializationException when this happens.
It would be nicer to get a MailChimpAPIException of some kind, ideally including the first n characters of the page body.

This is the exception we get:
System.Runtime.Serialization.SerializationException : Type definitions should start with a '{', expecting serialized type 'ApiError', got string starting with: <HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>
An e...

**Comment by danesparza** [comment]
This is a great point.  It'd be nice if we could get an easily reproducible case.  The next time this happens, can you see if it's dropping into this [exception handler here](https://github.com/danesparza/MailChimp.NET/blob/master/MailChimp/MailChimpManager.cs#L3256-3264)?

**Comment by htoomik** [comment]
Yes, it looks like that's where we end up. Here's the stack trace:

```
System.AggregateException: One or more errors occurred. ---> System.Runtime.Serialization.SerializationException: Type definitions should start with a '{', expecting serialized type 'ApiError', got string starting with: <HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY> An e
at ServiceStack.Text.Common.DeserializeTypeRefJson.StringToType(Type type, String strType, EmptyCtorDelegate ctorFn, Dictionary`2 typeAccessorMap)
at ServiceStack.Text.JsonSerializer.DeserializeFromString[T](String value)
at MailChimp.MailChimpManager.MakeAPICall[T](String apiAction, Object args)
at ReQtest.Data.Commands.MailChimp.MailChimpApiFacade.<>c__DisplayClass12.<BatchSubscribeToList>b__e() in c:\TeamCity\buildAgent\work\5df5e08f77af18ac\src\WebApp\ReQtest.Data\Commands\MailChimp\MailChimpApiFacade.cs:line 96
at System.Threading.Tasks.Task`1.InvokeFuture(Object futureAsObj)
at System.Threading.Tasks.Task.Execute()
--- End of inner exception stack trace ---
...
```
